### ISSUE TITLE
Use Case Diagrams

### ISSUE THREAD

**Issue by manna8** [PabloDelHoyo/ISO2-2022-A02#1]
- [x] Create and add to wiki Use Case Diagrams

**Comment by ferpotenUCLM** [comment]
![Pilgrimfy](https://user-images.githubusercontent.com/115221495/202323481-dbe3e42e-d6cd-42a8-8b27-51ed3dbfc08c.jpg)

**Comment by ferpotenUCLM** [comment]
I have uploaded version 0.1.1 to the server in which the owner and client are modeled within the system.
It remains to add the administrator and model its use cases.
It is important to note that this is the first version and is still subject to change.

**Comment by ferpotenUCLM** [comment]
![Pilgrimfy_0 1 0](https://user-images.githubusercontent.com/115221495/202326021-b191341f-58e0-4fb9-9719-ffd9669dfcf4.jpg)

**Comment by ferpotenUCLM** [comment]
Issue corrected

**Comment by ferpotenUCLM** [comment]
New error spoted renaming to v1.0.1

**Comment by ferpotenUCLM** [comment]
Correcting issue .... Server Application actor lacking in admin diagram

**Comment by ferpotenUCLM** [comment]
![Pilgrimfy_prim](https://user-images.githubusercontent.com/115221495/202425294-6f43faf7-ba18-44be-9757-d8fe5fd04c17.jpg)
![Pilgrimfy_user](https://user-images.githubusercontent.com/115221495/202407790-0dccf37e-f3c4-4c51-b725-84978068971c.jpg)
![Pilgrimfy_buss](https://user-images.githubusercontent.com/115221495/202425278-c9d2b4be-e8fd-4b6c-80e4-e07b73f4cf38.jpg)
![Pilgrimfy_admin](https://user-images.githubusercontent.com/115221495/202407791-5b91e82e-a784-4700-a39f-78e9e6b5b23b.jpg)

**Comment by ferpotenUCLM** [comment]
v1.0.0 upload and updated in the wiki

**Comment by ferpotenUCLM** [comment]
v0.1.0 updated to wiki . This version is subject to change in the future !!
