### ISSUE TITLE
Cost and Time estimation

### ISSUE THREAD

**Issue by manna8** [PabloDelHoyo/ISO2-2022-A02#2]
- [x] Create tables for time estimation
- [x] Fill tables for time estimation
- [x] Make a calendar
- [x] Create tables for cost estimation
- [x] Fill tables for cost estimation

**Comment by manna8** [comment]
We decided that cost for an working hour is 25€, but for each part of iteration shouldn't it be multiplied by 2? 
If group 1 has to do e.g. Analysis and Reqs, team's work will take 5 h (each member has to work 5 hours), so the sum of working hours for this part is 10, right? Then cost is not 25€ * 5, but 25€ * 10.

**Comment by PabloDelHoyo** [comment]
Exactly, it should be multiplied by the number of people working in that part. Even though they working collaborately, they are paid independently.

**Comment by manna8** [comment]
Okay, I've changed budged estimation as agreed. Every other part is done, I'm closing the issue.
